export const  POST_OF_FOLLOWING_REQUEST="POST_OF_FOLLOWING_REQUEST";
export const  POST_OF_FOLLOWING_SUCCESS="POST_OF_FOLLOWING_SUCCESS";
export const  POST_OF_FOLLOWING_FAILURE="POST_OF_FOLLOWING_FAILURE";

export const  LIKE_REQUEST="LIKE_REQUEST";
export const  LIKE_SUCCESS="LIKE_SUCCESS";
export const  LIKE_FAILURE="LIKE_FAILURE";

export const  ADD_COMMENT_REQUEST="ADD_COMMENT_REQUEST";
export const  ADD_COMMENT_SUCCESS="ADD_COMMENT_SUCCESS";
export const  ADD_COMMENT_FAILURE="ADD_COMMENT_FAILURE";

export const  DELETE_COMMENT_REQUEST="DELETE_COMMENT_REQUEST";
export const  DELETE_COMMENT_SUCCESS="DELETE_COMMENT_SUCCESS";
export const  DELETE_COMMENT_FAILURE="DELETE_COMMENT_FAILURE";

export const  NEW_POST_REQUEST="NEW_POST_REQUEST";
export const  NEW_POST_SUCCESS="NEW_POST_SUCCESS";
export const  NEW_POST_FAILURE="NEW_POST_FAILURE";

export const  UPDATE_CAPTION_REQUEST="UPDATE_CAPTION_REQUEST";
export const  UPDATE_CAPTION_SUCCESS="UPDATE_CAPTION_SUCCESS";
export const  UPDATE_CAPTION_FAILURE="UPDATE_CAPTION_FAILURE";


export const  DELETE_POST_REQUEST="DELETE_POST_REQUEST";
export const  DELETE_POST_SUCCESS="DELETE_POST_SUCCESS";
export const  DELETE_POST_FAILURE="DELETE_POST_FAILURE";

export const  UPDATE_PROFILE_REQUEST="UPDATE_PROFILE_REQUEST";
export const  UPDATE_PROFILE_SUCCESS="UPDATE_PROFILE_SUCCESS";
export const  UPDATE_PROFILE_FAILURE="UPDATE_PROFILE_FAILURE";

export const  DELETE_PROFILE_REQUEST="DELETE_PROFILE_REQUEST";
export const  DELETE_PROFILE_SUCCESS="DELETE_PROFILE_SUCCESS";
export const  DELETE_PROFILE_FAILURE="DELETE_PROFILE_FAILURE";

export const  UPDATE_PASSWORD_REQUEST="UPDATE_PASSWORD_REQUEST";
export const  UPDATE_PASSWORD_SUCCESS="UPDATE_PASSWORD_SUCCESS";
export const  UPDATE_PASSWORD_FAILURE="UPDATE_PASSWORD_FAILURE";

export const  FORGOT_PASSWORD_REQUEST="FORGOT_PASSWORD_REQUEST";
export const  FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS";
export const  FORGOT_PASSWORD_FAILURE="FORGOT_PASSWORD_FAILURE";

export const  RESET_PASSWORD_REQUEST="RESET_PASSWORD_REQUEST";
export const  RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS";
export const  RESET_PASSWORD_FAILURE="RESET_PASSWORD_FAILURE";

export const  FOLLOW_USER_REQUEST="FOLLOW_USER_REQUEST";
export const  FOLLOW_USER_SUCCESS="FOLLOW_USER_SUCCESS";
export const  FOLLOW_USER_FAILURE="FOLLOW_USER_FAILURE";

export const  MY_POSTS_REQUEST="MY_POSTS_REQUEST";
export const  MY_POSTS_SUCCESS="MY_POSTS_SUCCESS";
export const  MY_POSTS_FAILURE="MY_POSTS_FAILURE";

export const  GET_POSTS_REQUEST="GET_POSTS_REQUEST";
export const  GET_POSTS_SUCCESS="GET_POSTS_SUCCESS";
export const  GET_POSTS_FAILURE="GET_POSTS_FAILURE";

export const  USER_POSTS_REQUEST="USER_POSTS_REQUEST";
export const  USER_POSTS_SUCCESS="USER_POSTS_SUCCESS";
export const  USER_POSTS_FAILURE="USER_POSTS_FAILURE";

export const  CLEAR_ERRORS="CLEAR_ERRORS";
export const  CLEAR_MESSAGE="CLEAR_MESSAGE";





