export const  REGISTER_USER_REQUEST="REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE="REGISTER_USER_FAILURE";

export const  LOGIN_USER_REQUEST="LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE="LOGIN_USER_FAILURE";

export const  LOAD_USER_REQUEST="LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS="LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE="LOAD_USER_FAILURE";

export const  LOGOUT_USER_REQUEST="LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS="LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE="LOGOUT_USER_FAILURE";

export const  ALL_USERS_REQUEST="ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS="ALL_USERS_SUCCESS";
export const ALL_USERS_FAILURE="ALL_USERS_FAILURE";

export const  USER_PROFILE_REQUEST="USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS="USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE="USER_PROFILE_FAILURE";